USE gradus;
CREATE TABLE users (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	forename VARCHAR(100) NOT NULL,
	surname VARCHAR(100) NOT NULL,
	password_hash VARCHAR(60) NOT NULL,
	role ENUM('user','admin') NOT NULL DEFAULT 'user',
	status ENUM('active','suspended') NOT NULL DEFAULT 'active',
	last_login_at TIMESTAMP NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
