USE gradus;
CREATE TABLE pending_registrations (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	forename VARCHAR(100) NOT NULL,
	surname VARCHAR(100) NULL,
	password_hash VARCHAR(60) NOT NULL,
	verification_code_hash VARCHAR(60) NOT NULL,
	code_expires_at TIMESTAMP NOT NULL,
	verification_attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
	resend_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
	last_code_sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);