USE gradus;
CREATE TABLE password_resets (
	user_id INT UNSIGNED PRIMARY KEY,
	reset_token_hash CHAR(64) NOT NULL,
	token_expires_at TIMESTAMP NOT NULL,
	resend_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
	last_token_sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	CONSTRAINT fk_password_resets_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);